project:
  type: website
  output-dir: docs

website:
  title: "Mathematical Art and Creative Coding"
  site-url: "https://georgemsavva.github.io/creativecoding/"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: superhero
    css: styles.css